config/routes.rb
Rails.application.routes.draw do
  get 'websites/index'

  resources :websites

  root 'websites#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/website.rb
class Website < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  def index
    @websites = Website.all
  end

  def new
  end

  def show
    @websites = Website.find params[:id]
    redirect_to @websites.url
  end

  def create

    @website = Website.new(params.require(:website).permit(:url))

    @website = Website.new(website_params)

    @website.save
    redirect_to :root
  end

  private
  def website_params
    params.require(:website).permit(:url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/websites/index.html.erb
<h1>List of URL's</h1>

<table>
  <tr>
    <th>ID</th>
    <th>URL</th>
  </tr>

  <% @websites.each do |website| %>
    <tr>
      <td><%= website.id %></td>
      <td><%= website.url %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to 'New URL', '/websites/new' %></p>

app/views/websites/new.html.erb
<h1>New URL to be Shortened</h1>

<%= form_with scope: :website, url: websites_path, local: true do |form| %>
  <p>
    <%= form.label :url %><br>
    <%= form.text_field :url %>
  </p>

  <p>
    <%= form.submit %>
  </p>

  <p><%= link_to 'Back to Index', :root %></p>
<% end %>